##
# Site settings
##

url:                "https://ecridge.com"
title:              Eden Cridge
email:              eden.cridge@gmail.com
pgp_key:            DD659648
github_username:    ecridge
description: >
  I&rsquo;m a software engineer with a physics degree. I enjoy learning
  languages, solving puzzles and generally being creative.


##
# Build settings
##

excerpt_separator:  <!--fold-->
exclude:            ["README.md", "js/motion.js"]
markdown:           kramdown
permalink:          /:year/:month/:day/:title/
paginate:           3
paginate_path:      "/side/:num/"
timezone:           Europe/London

##
# Dependencies
##

plugins: [jekyll-paginate]


##
# Markdown settings
##

# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - smart  # Automatic en -- and em -- dashes.
#     - no_intra_emphasis  # Straight up foo_bar_baz.
#     - tables
#     - disable_indented_code_blocks
#     - strikethrough  # ~~Ew.~~ Use double tildes.
#     - space_after_headers  #Don’t let headers touch the pound sign.
#     - superscript  # This is the 2^(nd) best extension.
#     - underline  # Distinguishes _underline_ from *emphasis*.
#     - highlight  # Make text ==stand out==.
#     - footnotes  # This could be useful.[^1]

# [^1]: Or at least I think it could be.
